name: queen
description: core app
version: 0.0.1
author: Ahmed Masoud
publish_to: "none"
# homepage:
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  easy_localization: ^3.0.0
  edge_alerts: ^0.0.1
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0
  logger: ^1.0.0
  queen_validators: ^0.2.3
  shared_preferences: ^2.0.5

  # * assets picker
  wechat_assets_picker: ^6.0.0
  google_maps_flutter: ^2.0.6
  google_map_location_picker:
    git:
      url: git://github.com/athul-ain/google_map_location_picker.git
      ref: 0eca611

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter: null
